//! Implementation detail of the [`derive_aliases`](https://docs.rs/derive_aliases/latest/) crate.
#![allow(rustdoc::invalid_rust_codeblocks)]

use crate::tokens::IntoTokens;
use crate::tokens::PathSeparator;
use proc_macro::{Delimiter, Group, Ident, Punct, Span, TokenStream, TokenTree};
use proc_macro::{Literal, Spacing};
use std::collections::HashSet;
use std::collections::{BTreeSet, HashMap};
use tokens::CompileError;
use tokens::Path;
use tokens::TokensIter;

mod define;
mod derive;
mod tokens;

/// Returns `all()`, a cfg predicate that ,
fn cfg_true() -> TokenStream {
    TokenStream::from_iter([
        TokenTree::Ident(Ident::new("all", Span::call_site())),
        TokenTree::Group(Group::new(Delimiter::Parenthesis, TokenStream::new())),
    ])
}

/// Define derive aliases that can be used in [`#[derive]`](macro@derive)
///
/// ```rust
/// # /*
/// derive_aliases::define! {
///     Copy = ::core::marker::Copy, ::core::clone::Clone;
///     Eq = ::core::cmp::Eq, ::core::cmp::PartialEq;
///     Ord = ..Eq, ::core::cmp::Ord, ::core::cmp::PartialOrd;
///     StdTraits = ..Copy, ..Ord, ::core::hash::Hash, ::core::fmt::Debug;
/// }
/// # */
/// ```
///
/// Alias declarations end with `;`. On the left of the `=` is name of the alias, and on the right are the derives it expands to, separated by commas.
///
/// See the [crate-level](https://docs.rs/derive_aliases/latest/derive_aliases) documentation for details"
#[allow(unused_assignments)]
#[proc_macro]
pub fn define(tts: TokenStream) -> TokenStream {
    define::define(tts)
}

/// Like [`#[std::derive]`](https://doc.rust-lang.org/reference/attributes/derive.html), but with support for derive aliases generated by [`#[define]`](macro@define)
///
/// ```rust
/// # /*
/// mod derive_alias {
///     // 1. Define the aliases
///     derive_aliases::define! {
///         Copy = ::core::marker::Copy, ::core::clone::Clone;
///         Eq = ::core::cmp::Eq, ::core::cmp::PartialEq;
///         Ord = ..Eq, ::core::cmp::Ord, ::core::cmp::PartialOrd;
///         StdTraits = ..Copy, ..Ord, ::core::hash::Hash, ::core::fmt::Debug;
///     }
/// }
///
/// use derive_aliases::derive;
///
/// // 2. Use the aliases
/// #[derive(..StdTraits)]
/// struct Example;
/// # */
/// ```
///
/// The above expands to:
///
/// ```
/// # /*
/// #[derive(Copy, Clone, Eq, PartialEq, Ord, PartialOrd, ::core::hash::Hash, Debug)]
/// struct Example;
/// # */
/// ```
///
/// See the [crate-level](https://docs.rs/derive_aliases/latest/derive_aliases) documentation for details
#[proc_macro_attribute]
pub fn derive(attr: TokenStream, item: TokenStream) -> TokenStream {
    derive::derive(TokenStream::new(), attr, item)
}

/// Emits the final item with its attributes.
///
/// This is a proc macro (not a `macro_rules!`) because the `#[derive]` attributes
/// generated by the alias expansion go through `macro_rules!` and end up in a
/// different hygiene context. Some derive macros (e.g. `linearize::Linearize`) use
/// `quote_spanned!` which mixes `input.span` with `call_site()`. When `call_site()`
/// is in the `macro_rules!` hygiene context, it can't resolve identifiers like `self`
/// defined at `input.span`.
///
/// By remapping all spans to `mixed_site()`, we strip the macro_rules hygiene marks
/// and place everything in a uniform context that derive macros can work with.
#[doc(hidden)]
#[proc_macro]
pub fn __internal_emit(input: TokenStream) -> TokenStream {
    let mut input = input.into_iter();
    let attrs = next_group(&mut input);
    let item = next_group(&mut input);

    TokenStream::from_iter(
        remap_spans(attrs)
            .into_iter()
            .chain(remap_spans(item)),
    )
}

/// Recursively remaps the hygiene context of all spans to `mixed_site()`
/// while preserving their source locations (for error messages and IDE features).
///
/// `Span::resolved_at` keeps the source location of the original span but adopts
/// the name resolution behavior of the target span (`mixed_site()`), stripping
/// any `macro_rules!` hygiene marks that would cause derive macros to fail.
fn remap_spans(stream: TokenStream) -> TokenStream {
    stream
        .into_iter()
        .map(|mut tt| {
            match &tt {
                TokenTree::Group(g) => {
                    let mut new_group = Group::new(g.delimiter(), remap_spans(g.stream()));
                    new_group.set_span(g.span().resolved_at(Span::mixed_site()));
                    tt = TokenTree::Group(new_group);
                }
                _ => {
                    tt.set_span(tt.span().resolved_at(Span::mixed_site()));
                }
            }
            tt
        })
        .collect()
}

#[doc(hidden)]
#[proc_macro]
pub fn fold_attr(input: TokenStream) -> TokenStream {
    let mut input = input.into_iter();
    let attributes_before = next_group(&mut input);
    let derive_args = next_group(&mut input);
    let item = next_group(&mut input);

    derive::derive(attributes_before, derive_args, item)
}

/// Extracts the stream from the next `Group` token in the iterator.
fn next_group(input: &mut impl Iterator<Item = TokenTree>) -> TokenStream {
    match input.next() {
        Some(TokenTree::Group(g)) => g.stream(),
        _ => unreachable!(),
    }
}

/// The macro **created** by `new_alias!` handles de-duplication just fine using a TT muncher. But the derives passed to `new_alias!` **must not**
/// have any duplicates in them. This can happen if the alias refers to an "extern alias" (alias defined outside of this `define!` call), like here:
///
/// ```ignore
/// derive_aliases::define! {
///     Eq = ::core::cmp::Eq, ::core::cmp::PartialEq;
/// }
/// derive_aliases::define! {
///     EqEq = ..Eq, ..Eq;
/// }
/// ```
///
/// The above generates this, which contains duplicated derive paths:
///
/// ```ignore
/// crate::__internal_derive_aliases_new_alias! {
///     "..." a $ EqEq! [ { true } ::core::cmp::Eq],[ { true } ::core::cmp::PartialEq],[ { true } ::core::cmp::Eq],[ { true } ::core::cmp::PartialEq],
/// }
/// ```
///
/// So instead of that, we nest the arguments inside of a call to this macro, which de-duplicates the derives we pass to `new_alias!`:
///
/// ```ignore
/// crate::__internal_derive_aliases_new_alias_with_externs! {
///     a $ EqEq!
///     [ { true } ::core::cmp::Eq],[ { true } ::core::cmp::PartialEq],[ { true } ::core::cmp::Eq],[ { true } ::core::cmp::PartialEq],
/// }
/// ```
///
/// This expands to this:
///
/// ```ignore
/// crate::__internal_derive_aliases_new_alias! {
///     "..." a $ EqEq! [ { true } ::core::cmp::Eq],[ { true } ::core::cmp::PartialEq],
/// }
/// ```
///
/// Originally, this macro was just a TT muncher. However, to accurately generate the documentation `"..."` I made it
/// into a proc macro, so it also generates the `"..."` based off the aliases it contains
#[doc(hidden)]
#[proc_macro]
pub fn __internal_derive_aliases_new_alias_with_externs(ts: TokenStream) -> TokenStream {
    let mut ts = ts.into_iter().peekable();

    // a
    let visibility_mode = match ts.next() {
        Some(TokenTree::Ident(ident)) => ident,
        _ => unreachable!("first token is the visibility mode of the `macro_rules!` alias"),
    };

    // $
    let dollar = match ts.next() {
        Some(TokenTree::Punct(punct)) if punct == '$' => punct,
        Some(tt) => unreachable!(
            "second token is dollar for generating macro from macro: {}",
            tt
        ),
        _ => unreachable!("second token is dollar for generating macro from macro"),
    };

    // EqEq
    let alias = match ts.next() {
        Some(TokenTree::Ident(ident)) => ident,
        _ => unreachable!("third token is name of the actual alias"),
    };

    // !
    let exclam = match ts.next() {
        Some(TokenTree::Punct(punct)) if punct == '!' => punct,
        _ => unreachable!("fourth token is the `!`"),
    };

    // [ { true } ::core::cmp::Eq],[ { true } ::core::cmp::PartialEq],[ { true } ::core::cmp::Eq],[ { true } ::core::cmp::PartialEq],
    let mut paths = HashSet::new();

    // consume `[$($path:tt)*],` until there are none left
    while let Some(tt) = ts.next() {
        let mut group = match tt {
            TokenTree::Group(group) if group.delimiter() == Delimiter::Bracket => TokensIter {
                stream: group.stream().into_iter().peekable(),
                span: group.span(),
            },
            _ => unreachable!("every path is enclosed inside of `[...]`"),
        };

        // ignore the `cfg` for now
        let _ = group
            .group(Delimiter::Brace)
            .expect("first token is always `{ ... }`, containing the `cfg`");

        paths.insert(
            group
                .path()
                .expect("inside of `[...]` has an absolute path"),
        );

        match ts.next() {
            Some(TokenTree::Punct(punct)) if punct == ',' => (),
            _ => unreachable!("after the path `[...]` we always have a comma `,`"),
        }
    }

    // the inner stream passed to the actual `new_alias!`
    // with these changes:
    // - de-duplicated alias
    // - contains the real documentation
    let stream = TokenStream::from_iter(
        // lets re-construct the actual path
        [
            TokenTree::Literal(Literal::string(&generate_documentation_for_alias(
                &alias.to_string(),
                &paths,
            ))),
            TokenTree::Ident(visibility_mode),
            TokenTree::Punct(dollar),
            TokenTree::Ident(alias),
            TokenTree::Punct(exclam),
        ]
        .into_iter()
        // now at the end we just add all of the tokens
        .chain(paths.into_iter().flat_map(|path| {
            let cfg = cfg_true();

            // every path and its comma
            [
                TokenTree::Group(Group::new(
                    Delimiter::Bracket,
                    TokenStream::from_iter(
                        [TokenTree::Group(Group::new(Delimiter::Brace, cfg))]
                            .into_iter()
                            .chain(path.into_tokens()),
                    ),
                )),
                TokenTree::Punct(Punct::new(',', Spacing::Joint)),
            ]
        })),
    );

    TokenStream::from_iter([
        TokenTree::Punct(Punct::new(':', Spacing::Joint)),
        TokenTree::Punct(Punct::new(':', Spacing::Joint)),
        TokenTree::Ident(Ident::new("derive_aliases", Span::call_site())),
        TokenTree::Punct(Punct::new(':', Spacing::Joint)),
        TokenTree::Punct(Punct::new(':', Spacing::Joint)),
        TokenTree::Ident(Ident::new(
            "__internal_derive_aliases_new_alias",
            Span::call_site(),
        )),
        TokenTree::Punct(Punct::new('!', Spacing::Joint)),
        TokenTree::Group(Group::new(Delimiter::Brace, stream)),
    ])
}

/// Given an `alias` and its `expansion` (all derives it expands to, resolved recursively),
/// generates documentation about the alias to put in a `///` comment
fn generate_documentation_for_alias(alias: &str, expansion: &HashSet<Path>) -> String {
    const PRELUDE_PATHS: &[&str] = &[
        "core::marker::Copy",
        "core::clone::Clone",
        "core::fmt::Debug",
        "core::default::Default",
        "core::cmp::PartialEq",
        "core::cmp::Eq",
        "core::cmp::PartialOrd",
        "core::cmp::Ord",
    ];

    // We want to group each path by where it is located,
    // if we import a bunch of derives from `num_traits` then we want to group those
    // into a single `use`
    //
    // To do this we hash the path to the parent module/crate that contains the alias
    let mut grouped_by_parent = HashMap::new();

    let mut derive_contents = BTreeSet::new();

    for path in expansion {
        let mut components = path.components.clone();
        let derive = components
            .pop()
            .expect("Derive cannot be located at crate root")
            .1
            .to_string();

        let first_component = path.first_component.to_string();
        let first_component = if first_component == "std" {
            "core".to_string()
        } else {
            first_component
        };

        let path = Path {
            leading_colon: None,
            first_component: Ident::new(&first_component.to_string(), Span::call_site()),
            components,
        };

        let path_string = path.to_string();
        if PRELUDE_PATHS.contains(&format!("{path_string}::{derive}").as_str()) {
            // insert derive directly, without the `use`
            derive_contents.insert(derive);
            continue;
        }

        grouped_by_parent
            .entry(path)
            .or_insert_with(Vec::new)
            .push(derive);
    }

    derive_contents.extend(grouped_by_parent.values().flatten().cloned());

    let uses = grouped_by_parent
        .into_iter()
        .map(|(key, uses)| match &uses[..] {
            [single] => {
                format!("use {key}::{single}")
            }
            [..] => {
                if uses.len() >= 10 {
                    let content = uses.into_iter().collect::<Vec<_>>();
                    // format long list of derives in a more nice manner
                    let derives = content
                        .chunks(5)
                        .map(|derives| format!("    {},\n", derives.join(", ")))
                        .collect::<String>();
                    // remove trailing comma
                    if let Some(uses) = derives.strip_suffix(",\n") {
                        format!("\nuse {key}::{{{uses}}}\n")
                    } else {
                        format!("\nuse {key}::{{{derives}}}")
                    }
                } else {
                    format!("use {key}::{{{}}}", uses.join(", "))
                }
            }
        })
        .collect::<Vec<_>>()
        .join("\n");

    let derives = if derive_contents.len() >= 10 {
        let content = derive_contents.into_iter().collect::<Vec<_>>();
        // format long list of derives in a more nice manner
        let derives = content
            .chunks(5)
            .map(|derives| format!("    {},\n", derives.join(", ")))
            .collect::<String>();
        // remove trailing comma
        if let Some(derives) = derives.strip_suffix(",\n") {
            format!("\n{derives}\n")
        } else {
            format!("\n{derives}")
        }
    } else {
        derive_contents.into_iter().collect::<Vec<_>>().join(", ")
    };

    format!(
        "\
Derive alias `..{alias}` can be used like this:

```ignore
#[derive(..{alias})]
struct Example;
```

Which expands to the following:

```ignore
#[derive({derives})]
struct Example;{}{uses}
```",
        if uses.is_empty() { "" } else { "\n\n" },
    )
}
